
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.example.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRes03e136e implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 67;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("5b6578616d706c655d0d0a202020206c6f636174696f6e3d73");
        out.append("72632f6d61696e2f7265736f75726365732f6170706c696361");
        out.append("74696f6e2e70726f706572746965730d0a");

    }
}
