
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.stopper.res.t;

import java.util.ArrayList;
import java.util.List;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

// 这里限制为包内访问。如需从其它包访问 ，必须手工导出
final class EmbeddedResMain {

    private EmbeddedResMain() {        
    }

    public static List<EmbeddedRes> all() {
        List<EmbeddedRes> list = new ArrayList<>();

        // list.add(new ExampleEmbedRes84b6331());

        
        list.add(new EmbeddedRes84b6331());


        return list;
    }
}
