
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.stopper.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRescfe4754 implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 161;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("5b73746172746572202273746f70706572225d0d0a20202020");
        out.append("656e61626c6564203d20310d0a2020202073636f7065203d20");
        out.append("64656661756c740d0a20202020616374696f6e203d20646566");
        out.append("61756c740d0a20202020636f6e74726f6c2e66696c65203d20");
        out.append("7e2f2e737461727465722f64656661756c742e73746f707065");
        out.append("720d0a20202020636f6e74726f6c2e696e74657276616c203d");
        out.append("20313030300d0a20202020");

    }
}
