
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRes93a3a8c implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 304;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("0d0a5b64656275675d0d0a09656e61626c65643d310d0a096c");
        out.append("6f672d617267756d656e74733d310d0a096c6f672d656e7669");
        out.append("726f6e6d656e743d300d0a096c6f672d70726f706572746965");
        out.append("733d300d0a0d0a5b766c6f675d0d0a09666f726d6174746572");
        out.append("732e64656661756c742e666f726d61743d207b7b2e59454152");
        out.append("7d7d2d7b7b2e4d4f4e54487d7d2d7b7b2e4441597d7d207b7b");
        out.append("2e48487d7d3a7b7b2e4d4d7d7d3a7b7b2e53537d7d2e7b7b2e");
        out.append("5353537d7d207b7b2e5a4f4e457d7d20287b7b2e5441477d7d");
        out.append("29205b7b7b2e4c4556454c7d7d5d0d0a0967726f7570732e6d");
        out.append("61696e2e66696c746572733d64656661756c742d6c6f672d66");
        out.append("6f726d61747465722c636f6e736f6c652d6c6f672d77726974");
        out.append("65720d0a096c6576656c3d696e666f0d0a096d61696e3d6d61");
        out.append("696e0d0a");

    }
}
