
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedResd1dc061 implements EmbeddedRes {

    @Override
    public String path() {
        return "/banner.txt";
    }

    @Override
    public int size() {
        return 309;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("205f5f5f5f205f5f5f5f5f20205f202020205f5f5f5f205f5f");
        out.append("5f5f5f205f5f5f5f5f205f5f5f5f20200d0a2f205f5f5f7c5f");
        out.append("2020205f7c2f205c20207c20205f205c5f2020205f7c205f5f");
        out.append("5f5f7c20205f205c200d0a5c5f5f5f205c207c207c202f205f");
        out.append("205c207c207c5f29207c7c207c207c20205f7c207c207c5f29");
        out.append("207c0d0a205f5f5f29207c7c207c2f205f5f5f205c7c20205f");
        out.append("203c207c207c207c207c5f5f5f7c20205f203c200d0a7c5f5f");
        out.append("5f5f2f207c5f2f5f2f2020205c5f5c5f7c205c5f5c7c5f7c20");
        out.append("7c5f5f5f5f5f7c5f7c205c5f5c0d0a20202020202020202020");
        out.append("2020202020202020202020202020202020202020202020666f");
        out.append("72204a6176610d0a203a3a2053746172746572346a203a3a20");
        out.append("20287b7b737461727465722e6672616d65776f726b2e766572");
        out.append("73696f6e7d7d290d0a");

    }
}
