
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer  
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.example.embedres;

import java.util.ArrayList;
import java.util.List;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

public class ExampleMainRes {

    public static List<EmbeddedRes> all() {
        List<EmbeddedRes> list = new ArrayList<>();

        list.add(new ExampleEmbedRes84b6331());

        return list;
    }
}
