
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.res.t;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedResf187203 implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 116;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("0d0a5b6174202274657374225d0d0a096170706c6963617469");
        out.append("6f6e2e70726f706572746965733d7372632f746573742f7265");
        out.append("736f75726365730d0a0d0a090d0a090d0a5b61202262225d0d");
        out.append("0a09636f6d31203d20393532370d0a09636f6d32203d206869");
        out.append("2c7468697320697320636f6d320d0a09");

    }
}
