
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.res.t;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRes3c650a9 implements EmbeddedRes {

    @Override
    public String path() {
        return "/index.html";
    }

    @Override
    public int size() {
        return 350;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("3c21444f43545950452068746d6c3e0d0a3c68746d6c206c61");
        out.append("6e673d22656e223e0d0a0d0a3c686561643e0d0a202020203c");
        out.append("6d65746120636861727365743d225554462d38223e0d0a2020");
        out.append("20203c6d657461206e616d653d2276696577706f7274222063");
        out.append("6f6e74656e743d2277696474683d6465766963652d77696474");
        out.append("682c20696e697469616c2d7363616c653d312e30223e0d0a20");
        out.append("2020203c7469746c653e446f63756d656e743c2f7469746c65");
        out.append("3e0d0a0d0a202020203c6c696e6b2072656c3d227374796c65");
        out.append("73686565742220747970653d22746578742f63737322206872");
        out.append("65663d222e2f6373732f626173652e63737322202f3e0d0a3c");
        out.append("2f686561643e0d0a0d0a3c626f64793e0d0a202020203c6831");
        out.append("3e48656c6c6f3c2f68313e0d0a0d0a202020203c7363726970");
        out.append("74207372633d222e2f6a732f626173652e6a73223e3c2f7363");
        out.append("726970743e0d0a3c2f626f64793e0d0a0d0a3c2f68746d6c3e");

    }
}
