
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4j.vlog.simple.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRes84b6331 implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 0;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        

    }
}
